### ISSUE TITLE
Updating log levels doesn’t hide debug log lines

### ISSUE THREAD

**Issue by jakesgordon** [appsignal/appsignal-elixir-phoenix#8] opened 2020-12-16 00:24 UTC
Hello. Thanks for AppSignal. I'm looking forward to using it more!  

I know this is fairly trivial, but would it be possible to remove the unnecessary Logger.debug statements when we `use Appsignal.Phoenix` and `use Appsignal.Phoenix.View`

I try to keep my compilation steps clean, but now I've integrated Appsignal I get 3 debug statements every time my endpoint gets recompiled...

```
==> kevala
Compiling 58 files (.ex)
16:18:43.282 [debug] AppSignal.Phoenix.View attached to Elixir.Kevala.Api.ErrorView
16:18:43.309 [debug] AppSignal.Phoenix.View attached to Elixir.Kevala.Api.LayoutView
16:18:43.653 [debug] AppSignal.Plug attached to Elixir.Kevala.Api.Endpoint
```
I guess there's one in :appsignal_phoenix but also one in :appsignal_plug.

These seem unnecessary?

**Comment by jakesgordon** [comment] 2020-12-16 15:12
I guess my question is why do we need them at compile time? Shouldn't they be runtime log output?

**Comment by jeffkreeftmeijer** [comment] 2021-01-04 06:29
Hey @jakesgordon,

These get added at compile time because the attaching of the modules happens at compile time. Having them at compile time at least reduces the number of lines we’re outputting compared to doing it at runtime, where they’d happen whenever you call out through your endpoint.

Another option of doing this would be having the diagnose figure this out on demand. That way, we could ask the diagnose command which modules AppSignal was included in instead of having to search through logs.  We haven’t found a way to do that, yet, though.

**Comment by bobwaycott** [comment] 2021-01-09 19:41
Hey, I'm not sure if I'm doing something wrong or what, but in my test environment, I have `config :logger, level: :warn`, and I *still* see all the AppSignal debug log statements.

**Comment by jeffkreeftmeijer** [comment] 2021-01-11 06:56
Hey @bobwaycott,

Thanks for checking this. I’ll reopen this and will put it on the board to take a look at why that’s not working for you.

**Comment by bobwaycott** [comment] 2021-01-11 15:17
@jeffkreeftmeijer glad to figure out if it's something i've done wrong. If it helps, here's a quick rundown of the `config/config.exs` I'm working with, plus the `config/test.exs`, as well.

```elixir
# config/config.exs

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :trace_id, :span_id]

# environment variables set other required AppSignal attrs
config :appsignal, :config,
  otp_app: :pio,
  active: false
```

Even with `active: false`, I still see all `Logger.debug` statements out of AppSignal.

```
# config/test.exs

# Print only warnings and errors during test
config :logger, level: :warn
```

Still results in debug statements from AppSignal.

**Comment by jeffkreeftmeijer** [comment] 2021-01-18 10:06
Hey @bobwaycott,

It looks like you’re explicitly updating the logger configuration for the test environment, are you trying to clear log output from your test runs? If you’re still running into this, could you show me what log lines you’re seeing when running which commands? Also, do you have an example project I can try that reproduces this problem?

I’ve tested this again, and setting `config :logger, level: :info` in my `config/dev.exs` removes the following lines from my logs while running `mix phx.server`:

```
[debug] AppSignal starting
[debug] AppSignal started.
[debug] Appsignal.Error.Backend attached to Logger
[debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :start]
[debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :stop]
```

This seems to be working, so I’m closing this again. Please reopen (with an example project, preferably) if you’re still running into this issue.

**Closed by jeffkreeftmeijer** 2021-01-18 10:06 UTC
